{% set name = "xontrib-argcomplete" %}
{% set version = "0.2.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: a818afa5b60246a458c3d4ec819a3970bde4886f87fea0519559155d4031a7ea

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - argcomplete
    - xonsh

test:
  commands:
    - xonsh -c "xontrib load argcomplete"

about:
  home: https://github.com/anki-code/xontrib-argcomplete
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Support for argcomplete in xonsh
  doc_url: https://github.com/anki-code/xontrib-argcomplete/blob/master/README.md
  dev_url: https://github.com/anki-code/xontrib-argcomplete

extra:
  recipe-maintainers:
    - scopatz
