{% set name = "xontrib-argcomplete" %}
{% set version = "0.3.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 04d0d51776064b259665853b71a6dd5f5b2a94c47641aee193f00c18db0a1bc2

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - argcomplete
    - xonsh

test:
  commands:
    - xonsh -c "xontrib load argcomplete"

about:
  home: https://github.com/anki-code/xontrib-argcomplete
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Support for argcomplete in xonsh
  doc_url: https://github.com/anki-code/xontrib-argcomplete/blob/master/README.md
  dev_url: https://github.com/anki-code/xontrib-argcomplete

extra:
  recipe-maintainers:
    - scopatz
