{% set name = "xontrib-argcomplete" %}
{% set version = "0.3.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 9a9d652e91976a1e183138075f5757d0894f75287878e90a52f21b1dbc91a451

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - argcomplete
    - xonsh

test:
  commands:
    - xonsh -c "xontrib load argcomplete"

about:
  home: https://github.com/anki-code/xontrib-argcomplete
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Support for argcomplete in xonsh
  doc_url: https://github.com/anki-code/xontrib-argcomplete/blob/master/README.md
  dev_url: https://github.com/anki-code/xontrib-argcomplete

extra:
  recipe-maintainers:
    - scopatz
